### PR TITLE
Fix/mime content type

### LINKED ISSUE #909: Check if mime_content_type is available and show notification
### Description

From the uninstallation feedback we found that there was a mention of critical error:

> critical uncaught error Critical Uncaught Error: Call to undefined function mime_content_type() in /plugins/feedzy-rss-feeds/includes/admin/feedzy-rss-feeds-import.php:1979

It can happen on websites that don't have `mime_content_type` enable on the server but we should check this without generating a critical error on the website on those cases and showing to user that it should be enabled for Feedzy to work.

Should have been introduced here - https://github.com/Codeinwp/feedzy-rss-feeds/commit/6ceb36f9fb7c575cce2b7d3c0afcadfbd746e557

### Step-by-step reproduction instructions

Can be replicated by disabling mime_content_type on the server.

### Screenshots, screen recording, code snippet or Help Scout ticket

_No response_

### Environment info

_No response_

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by preda-bogdan**
### Summary

Will get the mime type of the imported image from the Header `Content-Type` of the image that is downloaded, if the `mime_content_type` function is available will also use that to ensure the proper type.

This will prevent fatal errors in instances where the `mime_content_type` function might not be present. 

Extended tests to also check for the attachments import.

### Will affect the visual aspect of the product

NO

### Test instructions

1. Unit tests should pass
2. On a fresh instance where `FileInfo` PHP extension is not present
3. Check that the import of a feed as an attachment will not trigger an error.

## Check before Pull Request is ready:

* [x] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes #909.

### CODE REVIEW

File: includes/admin/feedzy-rss-feeds-import.php [hunk 1]
```diff
@@ -2019,7 +2038,10 @@ private function try_save_featured_image( $img_source_url, $post_id, $post_title
 				return false;
 			}
 
-			$type = mime_content_type( $local_file );
+			$type = $this->get_file_type_by_url( $img_source_url );
```
Comment (GrigoreMihai) [inline includes/admin/feedzy-rss-feeds-import.php]: Everything looks good. 

I have a small optimization suggestion if you see the value in it. 

My suggestion would be first check if the `mime_content_type` function exists and if it does use it to get the mime type. If after this step the mime type is still empty then use the `get_file_type_by_url` function as this function will use more resources and we can avoid it if `mime_content_type` is present.

**Review by GrigoreMihai — APPROVED** [review]

File: includes/admin/feedzy-rss-feeds-import.php (hunk 1 above)
Comment (preda-bogdan) [reply includes/admin/feedzy-rss-feeds-import.php]: @GrigoreMihai thank you for the suggestion. I've made the changes, let me know if this looks good to you now.

Comment (GrigoreMihai) [reply includes/admin/feedzy-rss-feeds-import.php]: @preda-bogdan just a small thing, from what I know the check here will generate a notice https://github.com/Codeinwp/feedzy-rss-feeds/pull/912/commits/b02f7a6753996fd15068f3957ee3c3a106055c82#diff-ac43a0e8339b0e90d3b294b426f835842f98839ea6679134e46ebe11b4faaeabR2047 if the variable is undefined which could happen.

I suggest to initialize `$type` with an empty string, unless there is something that I'm missing. 

Apart from this all is good.
